"""
# @Time : 2022-02-07 17:27 

# @Author : sarah

# @File : 定位软键盘.py 

# @Software: PyCharm
"""
# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

driver = webdriver.Chrome()
driver.get("https://uat.cdcc.cmbchina.com/lending-express/unlimited-stage")
# driver.set_window_size(974, 1080)
#app > div > div.portal-body_19oiY > div.login_16dAY > div.login-content_2BrBo > div.login-content-card_2SqEg.half-border-bottom > input
driver.find_element(By.CSS_SELECTOR, "input").click()
driver.find_element(By.CSS_SELECTOR, "input").send_keys("533528202201018107")
time.sleep(5)
#app > div > div.portal-body_19oiY > div.login_16dAY > div.login-content_2BrBo > div.login-content-password_1I_NP.half-border-bottom > div.placeholder-msg_RN9zV
driver.find_element(By.CSS_SELECTOR, ".placeholder-msg_RN9zV").click()
time.sleep(5)
# driver.quit()
#<div class="keyboard-button-default_1x0-O" data-type="num">5</div>
#app > div > div.portal-body_19oiY > div.number-keyboard_bydnm.fade-out-animation_2j65p > ul > li:nth-child(1) > div
