# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

driver = webdriver.Chrome()



driver.get("https://www.zhipin.com/user/login.html")
driver.set_window_size(1936, 1096)
driver.implicitly_wait(5)
element = driver.find_element(By.CSS_SELECTOR, ".btn-outline:nth-child(2)")
actions = ActionChains(driver)
actions.move_to_element(element).perform()
element = driver.find_element(By.CSS_SELECTOR, "li:nth-child(1) .info-primary-wrap > .name")
actions = ActionChains(driver)
actions.move_to_element(element).perform()
element = driver.find_element(By.CSS_SELECTOR, "body")
actions = ActionChains(driver)
actions.move_to_element(element, 0, 0).perform()
element = driver.find_element(By.CSS_SELECTOR, "li:nth-child(1) .info-primary-wrap > .name")
actions = ActionChains(driver)
actions.move_to_element(element).perform()
element = driver.find_element(By.CSS_SELECTOR, "body")
actions = ActionChains(driver)
actions.move_to_element(element, 0, 0).perform()
driver.find_element(By.CSS_SELECTOR, "li:nth-child(1) .append .btn").click()
driver.find_element(By.CSS_SELECTOR, "li:nth-child(2) .append .btn").click()
element = driver.find_element(By.CSS_SELECTOR, "li:nth-child(2) .job-primary")
actions = ActionChains(driver)
actions.move_to_element(element).perform()
element = driver.find_element(By.CSS_SELECTOR, "body")
actions = ActionChains(driver)
actions.move_to_element(element, 0, 0).perform()
driver.find_element(By.CSS_SELECTOR, "li:nth-child(3) .append .btn").click()
element = driver.find_element(By.CSS_SELECTOR, "li:nth-child(4) .job-primary")
actions = ActionChains(driver)
actions.move_to_element(element).perform()
element = driver.find_element(By.CSS_SELECTOR, "body")
actions = ActionChains(driver)
actions.move_to_element(element, 0, 0).perform()
driver.find_element(By.CSS_SELECTOR, "li:nth-child(4) .append .btn").click()
driver.execute_script("window.scrollTo(0,403)")
element = driver.find_element(By.CSS_SELECTOR, "li:nth-child(5) .job-title")
actions = ActionChains(driver)
actions.move_to_element(element).perform()
element = driver.find_element(By.CSS_SELECTOR, "body")
actions = ActionChains(driver)
actions.move_to_element(element, 0, 0).perform()
driver.quit()
